# Generated by Django 2.2.14 on 2020-07-26 00:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200726_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='Sorry this post will be updated soon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
