# Generated by Django 2.2.14 on 2020-07-31 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200729_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='donationinfo',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='donationinfo',
            name='reference',
        ),
    ]
