# Generated by Django 3.0.8 on 2020-10-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='about_images1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='about_images2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='about_images3',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='blog_background_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='contact_background_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='homepage',
            field=models.ImageField(upload_to=''),
        ),
    ]
