# Generated by Django 3.1.3 on 2020-11-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_homepageabouttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageabouttext',
            name='website_name_on_homepage',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
