# Generated by Django 2.2.14 on 2020-07-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200722_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='phone_number',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='donation',
            name='reference_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
