# Generated by Django 2.2.14 on 2020-07-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200722_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=800)),
                ('image', models.ImageField(blank=True, default='user.svg', null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
