# Generated by Django 2.2.14 on 2020-07-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200724_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
