# Generated by Django 2.2.14 on 2020-07-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200726_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminfo',
            name='description',
            field=models.CharField(max_length=800),
        ),
    ]
