# Generated by Django 2.2.14 on 2020-07-31 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200731_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonationInfo',
        ),
    ]
