# Generated by Django 3.0.8 on 2020-10-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20201014_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'FooterLinks',
            },
        ),
    ]
