# Generated by Django 3.1.3 on 2020-11-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_homepageabouttext_website_name_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlinks',
            name='footer_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
