# Generated by Django 3.1.3 on 2020-11-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20201111_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageabouttext',
            name='website_name_on_homepage',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
